[build-system]
requires = ["setuptools>=62", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "thutil"
dynamic = ["version"]
requires-python = ">=3.8"
dependencies = []

### to use: pip install thamd[euler]
[project.optional-dependencies]
# llm = ['google-generativeai']


[tool.setuptools.dynamic]
version = { attr = "thutil.__version__" }

[tool.setuptools.packages.find]
include = ["thutil*"]
exclude = ["dev_tool*", "docs_site*"]

[tool.setuptools.package-data]
# thutil = ['_cookie_file/*']
